AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SAM Template for {{ cookiecutter.project_name }}
  
Globals:
  Function:
    Timeout: 3
    MemorySize: 128

Resources:
  {{cookiecutter.project_name | replace('-', '_')}}:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./{{cookiecutter.project_name}}/template.yaml
      # Optional parameter that can have default value overridden
#      Parameters:
