AWSTemplateFormatVersion: '2010-09-09'
Transform:
  - AWS::LanguageExtensions
  - AWS::Serverless-2016-10-31

Parameters:
  Project:
    Type: String
  ProjectGroup:
    Type: String
  Environment:
    Type: String

Resources:
  {{cookiecutter.module_name | replace('-', '_')}}:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./{{cookiecutter.module_name}}/template.yaml
      # Optional parameter that can have default value overridden
      Parameters:
        Project: !Ref Project
        ProjectGroup: !Ref ProjectGroup
        Environment: !Ref Environment
        TracingName: Fill it
