AWSTemplateFormatVersion: '2010-09-09'
Transform:
  - AWS::LanguageExtensions
  - AWS::Serverless-2016-10-31

Parameters:
  Company:
    Type: String
    Default: FR
  Project:
    Type: String
  ProjectLower:
    Type: String
  Vpc:
    Type: String
  ProjectGroup:
    Type: String
    Default: core-api
  Environment:
    Type: String
  Version:
    Type: String

Resources:
  {{cookiecutter.module_name | replace('-', '_')}}:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./{{cookiecutter.module_name}}/template.yaml
      # Optional parameter that can have default value overridden
      Parameters:
        Company: !Ref Company
        Project: !Ref Project
        ProjectLower: !Ref ProjectLower
        Vpc: !Ref Vpc
        ProjectGroup: !Ref ProjectGroup
        Environment: !Ref Environment
        Version: !Ref Version
